# Generated by Django 3.0.7 on 2020-07-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
