# Generated by Django 3.0.7 on 2020-08-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200828_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_by',
        ),
        migrations.DeleteModel(
            name='Fpo_Registeration',
        ),
    ]
