# Generated by Django 3.0.7 on 2020-08-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200828_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpo_Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpo_name', models.CharField(max_length=50)),
                ('fpo_area', models.CharField(max_length=50)),
                ('area_pincode', models.IntegerField()),
                ('total_members', models.IntegerField()),
                ('fpo_img', models.ImageField(upload_to='images/FPO')),
                ('description', models.TextField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='store.Fpo_Registeration'),
        ),
    ]
