# Generated by Django 3.0.7 on 2020-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200828_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpo_registeration',
            name='description',
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
