# Generated by Django 3.0.7 on 2020-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200831_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_email',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
