# Generated by Django 3.0.7 on 2020-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_fpo_registeration_fpo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpo_registeration',
            name='fpo_username',
            field=models.TextField(),
        ),
    ]
