# Generated by Django 3.0.7 on 2020-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200831_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpo_registeration',
            name='area_pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fpo_registeration',
            name='total_members',
            field=models.IntegerField(null=True),
        ),
    ]
