# Generated by Django 3.0.7 on 2020-09-04 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_auto_20200831_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpo_registeration',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Grain', 'Grain'), ('Fruit', 'Fruits')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(default='static/images/cart.png', upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(default='static/images/cart.png', upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(default='static/images/cart.png', upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img4',
            field=models.ImageField(default='static/images/cart.png', upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img5',
            field=models.ImageField(default='static/images/cart.png', upload_to='images/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
