# Generated by Django 3.0.7 on 2020-09-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200904_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(default='ecommerce\\static\\images\\cart.png', upload_to='images/product'),
        ),
    ]
