# Generated by Django 3.0.7 on 2020-09-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200904_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
